name: Alex Evans
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Brokering Excellence - Commercial Real Estate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#009788'
    - '#f9f9f9'
    - '#00695b'
    - '#7cdeeb'
    - '#64948d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
