name: Alex Evans
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Brokering Excellence - Commercial Real Estate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dee7f0'
    - '#647940'
    - '#141613'
    - '#ae9c88'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
