name: Alex Evans
favicon: null
layout_spectrum: 0.62384
typography_spectrum: 0.31746
title: Brokering Excellence - Commercial Real Estate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3593d1'
    - '#606261'
    - '#a4a4a4'
    - '#77c2ec'
  brandStrength: 0.625
  lightness: 0.21501228585839272
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
