name: Alex Evans
favicon: null
layout_spectrum: 0.9622984195593745
typography_spectrum: 0.07746029016561806
title: Brokering Excellence - Commercial Real Estate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5781992301344872
  lightness: 0.21501228585839272
  saturation: 0.0681187475565821
  rhythmicContrast: 0.7296411616262048
purpose: []
