name: Alex Evans
favicon: null
layout_spectrum: 0.62384
typography_spectrum: 0.31746
title: Brokering Excellence - Commercial Real Estate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#727274'
    - '#c9cdd8'
    - '#33363c'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
